INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(100, 'SALARY', 'EUR', 'Hindrek', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(200, 'RENT', 'EUR', 'Hindrek', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(250, 'SALARY', 'EUR', 'Hindrek', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(1000, 'GIFT', 'EUR', 'Hindrek', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)
VALUES(3500, 'OTHER', 'EUR', 'Hindrek', CURRENT_TIMESTAMP);

